server:
  port: 8012

spring:
  application:
    name: microservice-consumer-movie-ribbon-without-eureka

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#禁用Eureka
ribbon:
  eureka:
   enabled: false

microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
    