security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

server:
  port: 8050
  
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb #Max file size，默认1M
      max-request-size: 2500Mb #Max request size，默认10M
  
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
