server:
  port: 8088
  
#thymeleaf-springboot配置
spring:
  thymeleaf:
    cache: true #是否缓存，有缓存时会导致页面没法及时看到更新后的效果
    content-type: text/html; charset=utf-8
    enabled: true #是否启用
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#druid配置
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://192.168.0.173:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    # 数据源类型：Druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000 # 获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
#      connect-properties: 
#       druid: stat.mergeSql=true;druid.stat.sflowSqlMillis:500  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
 
 # Redis配置
  redis:
    host: 192.168.230.129 
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
     max-idle: 5000
     min-idle: 5
     max-active: 2000
     max-wait: 5000 
 #static    
  resources:
    add-mappings: true
    cache-period: 3600
    static-locations:
    - classpath:/static/
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
 #rabbitmq
#  rabbitmq:
#    host: 
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      simple:
#        concurrency: 10 #消费者数量
#        max-concurrency: 10
#        prefetch: 1 #每次从队列中取几个
#        auto-startup: true
#        default-requeue-rejected: true
#        retry:
#          enabled: true
#          initial-interval: 1000
#          max-interval: 10000
#          max-attempts: 3
#          multiplier: 1.0
          
        
#mybatis-springboot
mybatis:
    type-aliases-package: com.example.project.domain
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 3000


   