
#访问端口
server:
  port: 8010
#  context-path: /ribbon

spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix3

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
#    home-page-url-path: /ribbon
    metadata-map:
      management.port: 8081
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#管理端口
management:
  security:
    enabled: false
  port: 8081
    
hystrix.command.default.excution.isolation.thread.timeoutInMilliseconds: 5000
    