server:
  port: 7901

spring:
  application:
    name: microservice-provider-movice

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false
#超时的解决方案
#hystrix.command.default.excution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.command.default.excution.timeout.enabled: false
#feign.hystrix.enabled: false