
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/970064184/springcloud

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG
    
  
