server:
  port: 8013

spring:
  application:
    name: microservice-provider-movie-ribbon

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false
    
hystrix.command.default.excution.isolation.thread.timeoutInMilliseconds: 5000
    