server:
  port: 8013
  context-path: /ribbon

spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix2

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false
    
hystrix.command.default.excution.isolation.thread.timeoutInMilliseconds: 5000
    