server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/970064184/config-repo
  application:
    name: microservice-config-server-eureka
###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka #http://peer1:8761/eureka  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
          