server:
  port: 8011

spring:
  application:
    name: microservice-provider-movie-ribbon

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
microservice-provider-user:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #随机规则、加权规则

management:
  security:
    enabled: false
    