server:
  port: 7901

spring:
  application:
    name: microservice-provider-movice

###eureka提供者配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8761/eureka,http://peer3:8761/eureka #http://user:password123@localhost:8761/eureka
    healthcheck:
      enabled: true  
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false